Zsh configuration files.

* How to install

To install, run ~install.sh~, which copies the files in this directory to their
respective places.

* How to uninstall

To uninstall, run ~uninstall.sh~. This will remove the installed files.

* Secrets.sh

Upon start, Zsh is set up to source the file ~$HOME/.config/secrets.sh~. Put
whatever private info you need here. If this file does not exist, Zsh will warn,
but not fail.

* Zim, a module manager

~$ZDOTDIR~ is set to ~​$HOME/.config/zsh~ in ~​$HOME/.zshenv~.

Zim is a module manager for Zsh. By default it also sets up autocompletion,
useful aliases, etc.

Zim installs to ~$ZDOTDIR/.zim/~ (the default location) and is configured by
~$ZDOTDIR/.zimrc~. Zim installes a section in the ~.zshrc~ that sets it up.
After this section you can add your own additional configuration if you wish,
for example loading a theme.

The look of the prompt is set by themes. I took the existing theme "asciiship"
and made a few minor changes to it. See ~asciiship-djf/~. This is specfied in
the ~.zimrc~ file.

Other modules are also specified in ~.zimrc~. Put them at the end of the file.

Installation and removal of Zim modules are handled by ~zimfw~:

#+BEGIN_SRC sh
zimfw install   # Install new modules specified in .zimrc.
zimfw uninstall # Remove modules that were removed from .zimrc.
zimfw update    # Update modules to the latest version (if module included in the Zim repo.)
zimfw upgrade   # Upgrade Zim itself.
#+END_SRC

There are many other commands. ~zimfw help~ shows them all.
